### ISSUE TITLE
please add Webcam helper support on NVDA 2024.1

### ISSUE THREAD

**Issue by muhammadGagah** [OSadovy/webcam-helper-nvda-addon#9]
Hi, I've checked the NVDA logs about the Webcam helper add-on, and I'm using NVDA 2024.1, please fix this error if you have time.
```
ERROR - globalPluginHandler.listPlugins (22:35:09.886) - MainThread (7704):
Error importing global plugin webcamHelper
Traceback (most recent call last):
  File "C:\Users\muham\AppData\Roaming\nvda\addons\webcamHelper\globalPlugins\webcamHelper\3rdparty\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray
  File "C:\Users\muham\AppData\Roaming\nvda\addons\webcamHelper\globalPlugins\webcamHelper\3rdparty\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Users\muham\AppData\Roaming\nvda\addons\webcamHelper\globalPlugins\webcamHelper\3rdparty\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 23, in listPlugins
  File "importlib\__init__.pyc", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\muham\AppData\Roaming\nvda\addons\webcamHelper\globalPlugins\webcamHelper\__init__.py", line 11, in <module>
    import numpy as np
  File "C:\Users\muham\AppData\Roaming\nvda\addons\webcamHelper\globalPlugins\webcamHelper\3rdparty\numpy\__init__.py", line 150, in <module>
    from . import core
  File "C:\Users\muham\AppData\Roaming\nvda\addons\webcamHelper\globalPlugins\webcamHelper\3rdparty\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.11 from "C:\Program Files (x86)\NVDA\nvda.exe"
  * The NumPy version is: "1.21.6"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'
```

**Comment by OSadovy** [comment]
hey, NVDA upgraded python version and binary dependencies need to be recompiled. I'll try to look into this in the coming weeks. did not upgrade my NVDA version yet myself

**Comment by muhammadGagah** [comment]
Hi, have you made any improvements to this add-on? I don't have the knowledge to fix it.

**Comment by marrie** [comment]
I will upvote this. I went to use it and it shows as not compatible with nvda 2024. I really need this as I dont' want to launch the can you see me app.

**Comment by mjonsson1986** [comment]
same issue here

**Comment by Aleskis** [comment]
is there any chance of it being fixed?
